title: generic-api-google-assistant
hero_image: images/banner.png
subtitle: generic-api-google-assistant subtitle
description: generic-api-google-assistant description
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
published: false
steps:
  - title: Step one
    duration: 60
