title: Register the Google Assistant API
hero_image: images/banner.png
description: How to register the Google Assistant API
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
interests:
technology: "api"
steps:
  - title: Register the API
